Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,7 +15,7 @@ jobs:
     needs: action1
     steps:
       - name: Run Action 2
-        run: echo "Executing Action 3"
+        run: exit 1  # Force failure
 
 
   action3:
