Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -9,8 +9,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Run Action 1
-        run: echo "Executing Action 1"
-             exit 1  # Force failure
+        run: exit 1  # Force failure
 
   action2:
     runs-on: ubuntu-latest
